// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import AppKit
import Carbon.HIToolbox
import Foundation
import Sauce

/// Tier 2: pasteboard + synthesized ⌘V — the universal method.
///
/// Hardening (research: every shipping app's bug list):
///  - Snapshot ALL pasteboard item types and restore only if our write is still
///    current (changeCount + session-UUID marker type) — a user copy mid-flight wins.
///  - Transient/AutoGenerated marker types so clipboard managers skip the write.
///  - Layout-correct 'V' keycode via Sauce ('v' is 9 on QWERTY, 47 on Dvorak).
///  - Synthetic events tagged with SyntheticEventTag so our own tap ignores them.
///  - Restore delay ~1s (critic reconciliation #4) — slow apps read the pasteboard
///    late; a too-early restore pastes the user's OLD clipboard.
@MainActor
public final class PasteInserter {
    public static let restoreDelay: TimeInterval = 1.0
    private static let sessionMarker = NSPasteboard.PasteboardType("com.ammaar.jot.transient")
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    public init() {}

    private var restoreTask: Task<Void, Never>?

    /// Returns true if the ⌘V events were POSTED. There is no OS-level receipt
    /// that the frontmost app performed the paste (audit #12) — this is the
    /// industry floor; the transcript always remains recoverable from History
    /// and stays on the clipboard until restore.
    ///
    /// Returns RIGHT AFTER ⌘V posts — the ~1s clipboard restore runs in a
    /// background task so the session isn't pinned in .inserting for a second
    /// after the text visibly landed (production pass 2, P0: the next dictation's
    /// begin was silently rejected in that window).
    /// `keepingOnClipboard` suppresses the restore below, so the transcript stays
    /// pasteable and the previous clipboard does NOT come back — the deliberate
    /// cost of the setting. It also drops the transient markers: a transcript the
    /// user asked to keep is one their clipboard manager should be allowed to see.
    public func paste(_ text: String, keepingOnClipboard: Bool = false) async -> Bool {
        restoreTask?.cancel()
        let pasteboard = NSPasteboard.general
        let snapshot = Self.snapshot(pasteboard)

        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        if !keepingOnClipboard {
            item.setString(UUID().uuidString, forType: Self.sessionMarker)
            item.setString("", forType: Self.transientType)
            item.setString("", forType: Self.autoGeneratedType)
        }
        pasteboard.writeObjects([item])
        let ourChangeCount = pasteboard.changeCount

        // No settle sleep: writeObjects commits synchronously (changeCount has
        // already advanced above) and ⌘V is posted only after, so no reader can
        // observe the old pasteboard. The 100ms here was pure latency between
        // the transcript existing and the user seeing it.
        guard await Self.postCmdV() else {
            // Leave the text on the clipboard — it's the fallback content.
            return false
        }

        // The whole point of the setting: nothing takes the transcript back off.
        guard !keepingOnClipboard else { return true }

        restoreTask = Task { @MainActor in
            // ~1s (critic reconciliation #4): slow apps read the pasteboard late;
            // a too-early restore pastes the user's OLD clipboard.
            try? await Task.sleep(nanoseconds: UInt64(Self.restoreDelay * 1_000_000_000))
            guard !Task.isCancelled else { return }
            // Restore only if nothing else touched the pasteboard since our write.
            if pasteboard.changeCount == ourChangeCount,
               pasteboard.pasteboardItems?.first?.string(forType: Self.sessionMarker) != nil {
                Self.restore(snapshot, to: pasteboard)
            }
        }
        return true
    }

    /// Puts text on the clipboard WITHOUT restore — the tier-3 floor and the
    /// focus-changed path ("Copied — press ⌘V"). Marked transient so clipboard
    /// managers don't archive transcripts (audit L22) — unless `archivable`,
    /// which is the user having asked for exactly that.
    public func copyOnly(_ text: String, archivable: Bool = false) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        if !archivable {
            item.setString("", forType: Self.transientType)
        }
        pasteboard.writeObjects([item])
    }

    // MARK: - Plumbing

    /// First touch of `Sauce.shared` in a process pays a one-time Text Input
    /// Sources round-trip (34–61ms measured). Inside postCmdV that lands between
    /// transcript-ready and ⌘V, so pay it once at launch instead.
    public static func warmKeyboardLayout() {
        _ = Sauce.shared
    }

    private static func postCmdV() async -> Bool {
        guard let source = CGEventSource(stateID: .privateState) else { return false }
        let keyCode = CGKeyCode(Sauce.shared.keyCode(for: .v))
        guard let down = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true),
              let up = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false) else {
            return false
        }
        for event in [down, up] {
            event.flags = .maskCommand
            event.setIntegerValueField(.eventSourceUserData, value: SyntheticEventTag.magic)
        }
        down.post(tap: .cghidEventTap)
        // Yield, don't block: zero-gap synthetic keystrokes are dedupe-prone in
        // Chromium, but the wait belongs off the main thread.
        try? await Task.sleep(nanoseconds: 10_000_000)
        up.post(tap: .cghidEventTap)
        return true
    }

    private static func snapshot(_ pasteboard: NSPasteboard) -> [[NSPasteboard.PasteboardType: Data]] {
        (pasteboard.pasteboardItems ?? [])
            // Never chain-snapshot our own transient transcript from a previous
            // rapid-fire dictation whose restore hasn't run yet (audit L23).
            .filter { $0.string(forType: sessionMarker) == nil }
            .map { item in
                var entry: [NSPasteboard.PasteboardType: Data] = [:]
                for type in item.types {
                    if let data = item.data(forType: type) {
                        entry[type] = data
                    }
                }
                return entry
            }
    }

    private static func restore(_ snapshot: [[NSPasteboard.PasteboardType: Data]], to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        guard !snapshot.isEmpty else { return }
        let items = snapshot.map { entry -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in entry {
                item.setData(data, forType: type)
            }
            return item
        }
        pasteboard.writeObjects(items)
    }
}
